#!/usr/bin/env python3
"""Local IDE-like viewer for code-unit JSON generated by segment_code.py.

The viewer builds a compact SQLite index from a potentially very large JSON file,
then serves a local web UI with:
- expandable repository file tree
- original source view with unit boundary lines
- virtualized line rendering for large files
- unit list and unit detail inspector
- parse-error and warning indicators

Usage:
    python code_unit_viewer.py backend_unit.json
    python code_unit_viewer.py backend_unit.json --root D:\\project\\12_Gen_Code\\codegraph-mvp
"""

from __future__ import annotations

import argparse
import contextlib
import json
import mimetypes
import os
import sqlite3
import sys
import threading
import time
import urllib.parse
import webbrowser
from dataclasses import dataclass
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, Iterable, Iterator, Sequence

try:
    import ijson
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "ijson is required for large JSON files. Install it with: pip install ijson"
    ) from exc


VIEWER_VERSION = 2
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8765
MAX_SOURCE_BYTES = 30 * 1024 * 1024


INDEX_SCHEMA = """
PRAGMA journal_mode=DELETE;
PRAGMA synchronous=NORMAL;
PRAGMA temp_store=MEMORY;

CREATE TABLE IF NOT EXISTS metadata (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS files (
    file_path TEXT PRIMARY KEY,
    language TEXT NOT NULL,
    parse_has_error INTEGER NOT NULL,
    diagnostics_json TEXT NOT NULL,
    unit_count INTEGER NOT NULL,
    warning_count INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS units (
    id TEXT PRIMARY KEY,
    parent_id TEXT,
    file_path TEXT NOT NULL,
    ordinal INTEGER NOT NULL,
    language TEXT NOT NULL,
    node_type TEXT NOT NULL,
    kind TEXT NOT NULL,
    scope_role TEXT NOT NULL,
    depth INTEGER NOT NULL,
    start_line INTEGER NOT NULL,
    end_line INTEGER NOT NULL,
    display_start_line INTEGER NOT NULL,
    display_end_line INTEGER NOT NULL,
    start_column INTEGER NOT NULL,
    end_column INTEGER NOT NULL,
    code TEXT NOT NULL,
    raw_code TEXT NOT NULL,
    source_hash TEXT NOT NULL,
    warnings_json TEXT NOT NULL,
    warning_count INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_units_file_ordinal
ON units(file_path, ordinal);

CREATE INDEX IF NOT EXISTS idx_units_file_lines
ON units(file_path, start_line, end_line);

CREATE INDEX IF NOT EXISTS idx_units_parent
ON units(parent_id);
"""


@dataclass(frozen=True)
class ViewerConfig:
    json_path: Path
    db_path: Path
    source_root: Path
    host: str
    port: int
    open_browser: bool


class UnitIndex:
    def __init__(self, config: ViewerConfig) -> None:
        self.config = config
        self._local = threading.local()

    def connection(self) -> sqlite3.Connection:
        conn = getattr(self._local, "conn", None)
        if conn is None:
            conn = sqlite3.connect(self.config.db_path, check_same_thread=False)
            conn.row_factory = sqlite3.Row
            self._local.conn = conn
        return conn

    def cache_is_current(self) -> bool:
        if not self.config.db_path.exists():
            return False
        try:
            conn = sqlite3.connect(self.config.db_path)
            rows = dict(conn.execute("SELECT key, value FROM metadata"))
            conn.close()
        except (sqlite3.DatabaseError, OSError):
            return False

        stat = self.config.json_path.stat()
        expected = {
            "viewer_version": str(VIEWER_VERSION),
            "json_path": str(self.config.json_path.resolve()),
            "json_size": str(stat.st_size),
            "json_mtime_ns": str(stat.st_mtime_ns),
        }
        return all(rows.get(key) == value for key, value in expected.items())

    def rebuild(self) -> None:
        temp_path = self.config.db_path.with_suffix(self.config.db_path.suffix + ".tmp")
        with contextlib.suppress(FileNotFoundError):
            temp_path.unlink()

        conn = sqlite3.connect(temp_path)
        conn.executescript(INDEX_SCHEMA)

        root_value = read_single_json_value(self.config.json_path, "root")
        summary_value = read_single_json_value(self.config.json_path, "summary") or {}
        stat = self.config.json_path.stat()
        metadata = {
            "viewer_version": str(VIEWER_VERSION),
            "json_path": str(self.config.json_path.resolve()),
            "json_size": str(stat.st_size),
            "json_mtime_ns": str(stat.st_mtime_ns),
            "json_root": str(root_value or ""),
            "summary_json": json.dumps(summary_value, ensure_ascii=False),
            "indexed_at": str(int(time.time())),
        }
        conn.executemany(
            "INSERT INTO metadata(key, value) VALUES (?, ?)", metadata.items()
        )

        file_insert = """
            INSERT INTO files(
                file_path, language, parse_has_error, diagnostics_json,
                unit_count, warning_count
            ) VALUES (?, ?, ?, ?, ?, ?)
        """
        unit_insert = """
            INSERT INTO units(
                id, parent_id, file_path, ordinal, language, node_type, kind,
                scope_role, depth, start_line, end_line,
                display_start_line, display_end_line,
                start_column, end_column, code, raw_code, source_hash,
                warnings_json, warning_count
            ) VALUES (
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?, ?, ?, ?, ?
            )
        """

        indexed_files = 0
        indexed_units = 0
        with self.config.json_path.open("rb") as stream:
            for file_item in ijson.items(stream, "files.item"):
                file_path = str(file_item.get("file", ""))
                language = str(file_item.get("language", "unknown"))
                diagnostics = file_item.get("diagnostics") or []
                units = file_item.get("units") or []
                warning_count = sum(len(unit.get("warnings") or []) for unit in units)

                conn.execute(
                    file_insert,
                    (
                        file_path,
                        language,
                        1 if file_item.get("parse_has_error") else 0,
                        json.dumps(diagnostics, ensure_ascii=False),
                        len(units),
                        warning_count,
                    ),
                )

                unit_rows = []
                for ordinal, unit in enumerate(units):
                    warnings = unit.get("warnings") or []
                    start_line = int(unit.get("start_line", 1) or 1)
                    end_line = int(unit.get("end_line", 1) or 1)
                    display_start_line = int(
                        unit.get("display_start_line", start_line)
                        or start_line
                    )
                    display_end_line = int(
                        unit.get("display_end_line", end_line)
                        or end_line
                    )

                    unit_rows.append(
                        (
                            str(unit.get("id", "")),
                            unit.get("parent_id"),
                            file_path,
                            ordinal,
                            str(unit.get("language", language)),
                            str(unit.get("node_type", "")),
                            str(unit.get("kind", "statement")),
                            str(unit.get("scope_role", "")),
                            int(unit.get("depth", 0) or 0),
                            start_line,
                            end_line,
                            display_start_line,
                            display_end_line,
                            int(unit.get("start_column", 0) or 0),
                            int(unit.get("end_column", 0) or 0),
                            str(unit.get("code", "")),
                            str(unit.get("raw_code", "")),
                            str(unit.get("source_hash", "")),
                            json.dumps(warnings, ensure_ascii=False),
                            len(warnings),
                        )
                    )
                conn.executemany(unit_insert, unit_rows)

                indexed_files += 1
                indexed_units += len(unit_rows)
                if indexed_files % 20 == 0:
                    conn.commit()
                    print(
                        f"[index] files={indexed_files} units={indexed_units}",
                        flush=True,
                    )

        conn.execute(
            "INSERT OR REPLACE INTO metadata(key, value) VALUES (?, ?)",
            ("indexed_file_count", str(indexed_files)),
        )
        conn.execute(
            "INSERT OR REPLACE INTO metadata(key, value) VALUES (?, ?)",
            ("indexed_unit_count", str(indexed_units)),
        )
        conn.commit()
        conn.close()

        with contextlib.suppress(FileNotFoundError):
            self.config.db_path.unlink()
        temp_path.replace(self.config.db_path)
        print(
            f"[index] complete files={indexed_files} units={indexed_units} db={self.config.db_path}",
            flush=True,
        )

    def metadata(self) -> dict[str, Any]:
        conn = self.connection()
        values = dict(conn.execute("SELECT key, value FROM metadata"))
        summary = json.loads(values.get("summary_json", "{}"))
        return {
            "json_path": values.get("json_path"),
            "json_root": values.get("json_root"),
            "source_root": str(self.config.source_root),
            "summary": summary,
            "indexed_file_count": int(values.get("indexed_file_count", "0")),
            "indexed_unit_count": int(values.get("indexed_unit_count", "0")),
        }

    def list_files(self) -> list[dict[str, Any]]:
        rows = self.connection().execute(
            """
            SELECT file_path, language, parse_has_error, unit_count, warning_count
            FROM files
            ORDER BY file_path COLLATE NOCASE
            """
        )
        return [
            {
                "file": row["file_path"],
                "language": row["language"],
                "parse_has_error": bool(row["parse_has_error"]),
                "unit_count": row["unit_count"],
                "warning_count": row["warning_count"],
            }
            for row in rows
        ]

    def file_payload(self, file_path: str) -> dict[str, Any] | None:
        conn = self.connection()
        file_row = conn.execute(
            "SELECT * FROM files WHERE file_path = ?", (file_path,)
        ).fetchone()
        if file_row is None:
            return None

        marker_rows = conn.execute(
            """
            SELECT id, parent_id, ordinal, node_type, kind, scope_role, depth,
                   start_line, end_line,
                   display_start_line, display_end_line,
                   start_column, end_column, warning_count
            FROM units
            WHERE file_path = ?
            ORDER BY ordinal
            """,
            (file_path,),
        )
        markers = [dict(row) for row in marker_rows]

        source_result = self._read_source(file_path)
        return {
            "file": file_path,
            "language": file_row["language"],
            "parse_has_error": bool(file_row["parse_has_error"]),
            "diagnostics": json.loads(file_row["diagnostics_json"]),
            "unit_count": file_row["unit_count"],
            "warning_count": file_row["warning_count"],
            "markers": markers,
            **source_result,
        }

    def unit_payload(self, unit_id: str) -> dict[str, Any] | None:
        conn = self.connection()
        row = conn.execute("SELECT * FROM units WHERE id = ?", (unit_id,)).fetchone()
        if row is None:
            return None
        data = dict(row)
        data["warnings"] = json.loads(data.pop("warnings_json"))
        children = conn.execute(
            """
            SELECT id, ordinal, node_type, kind,
                   start_line, end_line,
                   display_start_line, display_end_line,
                   depth, warning_count
            FROM units
            WHERE parent_id = ?
            ORDER BY ordinal
            """,
            (unit_id,),
        )
        data["children"] = [dict(child) for child in children]
        return data

    def _read_source(self, file_path: str) -> dict[str, Any]:
        root = self.config.source_root.resolve()
        candidate = (root / Path(file_path)).resolve()
        try:
            candidate.relative_to(root)
        except ValueError:
            return {
                "source_available": False,
                "source_error": "File path escaped the configured source root.",
                "source": "",
            }

        if not candidate.exists() or not candidate.is_file():
            return {
                "source_available": False,
                "source_error": f"Source file not found: {candidate}",
                "source": "",
            }
        try:
            size = candidate.stat().st_size
            if size > MAX_SOURCE_BYTES:
                return {
                    "source_available": False,
                    "source_error": (
                        f"Source file is larger than {MAX_SOURCE_BYTES // (1024 * 1024)} MB: "
                        f"{candidate}"
                    ),
                    "source": "",
                }
            raw = candidate.read_bytes()
            source = raw.decode("utf-8-sig", errors="replace")
            return {
                "source_available": True,
                "source_error": None,
                "source": source,
            }
        except OSError as exc:
            return {
                "source_available": False,
                "source_error": str(exc),
                "source": "",
            }


def read_single_json_value(path: Path, prefix: str) -> Any:
    with path.open("rb") as stream:
        iterator = ijson.items(stream, prefix)
        return next(iterator, None)


def json_bytes(payload: Any, status: HTTPStatus = HTTPStatus.OK) -> tuple[int, bytes, str]:
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    return status.value, body, "application/json; charset=utf-8"


def make_handler(index: UnitIndex) -> type[BaseHTTPRequestHandler]:
    class ViewerHandler(BaseHTTPRequestHandler):
        server_version = "CodeUnitViewer/1.0"

        def log_message(self, fmt: str, *args: Any) -> None:
            sys.stdout.write("[http] " + (fmt % args) + "\n")

        def do_GET(self) -> None:  # noqa: N802
            parsed = urllib.parse.urlparse(self.path)
            query = urllib.parse.parse_qs(parsed.query)
            try:
                if parsed.path == "/":
                    self._send(HTTPStatus.OK.value, INDEX_HTML.encode("utf-8"), "text/html; charset=utf-8")
                    return
                if parsed.path == "/api/meta":
                    self._send_tuple(json_bytes(index.metadata()))
                    return
                if parsed.path == "/api/files":
                    self._send_tuple(json_bytes({"files": index.list_files()}))
                    return
                if parsed.path == "/api/file":
                    file_path = first_query_value(query, "path")
                    if not file_path:
                        self._send_tuple(json_bytes({"error": "path is required"}, HTTPStatus.BAD_REQUEST))
                        return
                    payload = index.file_payload(file_path)
                    if payload is None:
                        self._send_tuple(json_bytes({"error": "file not found"}, HTTPStatus.NOT_FOUND))
                        return
                    self._send_tuple(json_bytes(payload))
                    return
                if parsed.path == "/api/unit":
                    unit_id = first_query_value(query, "id")
                    if not unit_id:
                        self._send_tuple(json_bytes({"error": "id is required"}, HTTPStatus.BAD_REQUEST))
                        return
                    payload = index.unit_payload(unit_id)
                    if payload is None:
                        self._send_tuple(json_bytes({"error": "unit not found"}, HTTPStatus.NOT_FOUND))
                        return
                    self._send_tuple(json_bytes(payload))
                    return
                self._send_tuple(json_bytes({"error": "not found"}, HTTPStatus.NOT_FOUND))
            except BrokenPipeError:
                return
            except Exception as exc:  # pragma: no cover - runtime guard
                self._send_tuple(
                    json_bytes(
                        {"error": type(exc).__name__, "message": str(exc)},
                        HTTPStatus.INTERNAL_SERVER_ERROR,
                    )
                )

        def _send_tuple(self, response: tuple[int, bytes, str]) -> None:
            self._send(*response)

        def _send(self, status: int, body: bytes, content_type: str) -> None:
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)

    return ViewerHandler


def first_query_value(query: dict[str, list[str]], key: str) -> str | None:
    values = query.get(key)
    return values[0] if values else None


def choose_port(host: str, preferred: int) -> int:
    import socket

    for port in range(preferred, preferred + 20):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            try:
                sock.bind((host, port))
            except OSError:
                continue
            return port
    raise SystemExit(f"No available port found from {preferred} to {preferred + 19}")


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="View segment_code.py output in a local IDE-like UI.")
    parser.add_argument("json_file", type=Path, help="Path to backend_unit.json")
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Override source repository root stored in the JSON",
    )
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--no-browser", action="store_true")
    parser.add_argument("--rebuild-index", action="store_true")
    return parser.parse_args(argv)


def resolve_source_root(json_path: Path, override: Path | None) -> Path:
    if override is not None:
        return override.resolve()
    root_value = read_single_json_value(json_path, "root")
    if root_value:
        return Path(str(root_value)).resolve()
    return json_path.parent.resolve()


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    json_path = args.json_file.resolve()
    if not json_path.exists():
        raise SystemExit(f"JSON file does not exist: {json_path}")

    source_root = resolve_source_root(json_path, args.root)
    db_path = json_path.with_suffix(json_path.suffix + ".viewer.sqlite3")
    port = choose_port(args.host, args.port)
    config = ViewerConfig(
        json_path=json_path,
        db_path=db_path,
        source_root=source_root,
        host=args.host,
        port=port,
        open_browser=not args.no_browser,
    )
    index = UnitIndex(config)
    if args.rebuild_index or not index.cache_is_current():
        print(f"[index] building SQLite index from {json_path}", flush=True)
        index.rebuild()
    else:
        print(f"[index] using cache {db_path}", flush=True)

    server = ThreadingHTTPServer((config.host, config.port), make_handler(index))
    url = f"http://{config.host}:{config.port}/"
    print(f"[viewer] source_root={source_root}", flush=True)
    print(f"[viewer] open {url}", flush=True)
    if config.open_browser:
        threading.Timer(0.35, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[viewer] stopped", flush=True)
    finally:
        server.server_close()
    return 0


INDEX_HTML = r'''<main id="app">
  <header class="topbar">
    <div class="brand">Code Unit Viewer</div>
    <div class="metrics" id="metrics"></div>
    <label class="search-wrap">
      <span>파일 검색</span>
      <input id="fileSearch" type="search" placeholder="경로 또는 파일명" autocomplete="off">
    </label>
    <label class="check"><input id="warningOnly" type="checkbox"> 경고 파일만</label>
    <label class="check"><input id="errorOnly" type="checkbox"> 파싱 오류만</label>
  </header>

  <section class="workspace">
    <aside class="sidebar">
      <div class="pane-title">FILES <span id="visibleFileCount"></span></div>
      <div id="tree" class="tree" aria-label="파일 트리"></div>
    </aside>

    <section class="editor-pane">
      <div class="filebar">
        <div>
          <strong id="activeFile">파일을 선택하세요</strong>
          <span id="fileMeta" class="muted"></span>
        </div>
        <div class="tabs" role="tablist">
          <button id="sourceTab" class="tab active" type="button">Source</button>
          <button id="unitsTab" class="tab" type="button">Units</button>
        </div>
      </div>
      <div id="notice" class="notice hidden"></div>
      <div id="sourceView" class="view active">
        <div id="codeViewport" class="code-viewport" tabindex="0">
          <div id="codeCanvas" class="code-canvas"></div>
        </div>
      </div>
      <div id="unitsView" class="view">
        <div class="unit-toolbar">
          <label>단위 검색 <input id="unitSearch" type="search" placeholder="ID, 종류, 줄 번호"></label>
          <span id="unitCountLabel" class="muted"></span>
        </div>
        <div id="unitList" class="unit-list"><div id="unitListCanvas" class="unit-list-canvas"></div></div>
      </div>
    </section>

    <aside class="inspector">
      <div class="pane-title">UNIT INSPECTOR</div>
      <div id="emptyInspector" class="empty">경계선 또는 단위를 선택하세요.</div>
      <div id="unitInspector" class="hidden">
        <div class="inspector-head">
          <strong id="unitId"></strong>
          <span id="unitKind" class="badge"></span>
        </div>
        <dl class="meta-grid">
          <dt>줄</dt><dd id="unitLines"></dd>
          <dt>노드</dt><dd id="unitNode"></dd>
          <dt>깊이</dt><dd id="unitDepth"></dd>
          <dt>부모</dt><dd id="unitParent"></dd>
          <dt>역할</dt><dd id="unitRole"></dd>
        </dl>
        <div id="unitWarnings" class="warning-box hidden"></div>
        <h3>LLM 입력 코드</h3>
        <pre id="unitCode"></pre>
        <details>
          <summary>원본 범위</summary>
          <pre id="unitRaw"></pre>
        </details>
        <div id="unitChildrenWrap" class="hidden">
          <h3>자식 단위</h3>
          <div id="unitChildren" class="child-list"></div>
        </div>
      </div>
    </aside>
  </section>
</main>

<style>
  :root {
    color-scheme: light dark;
    --bg: #111318;
    --panel: #171a21;
    --panel-2: #1d212a;
    --border: #303642;
    --text: #e8eaf0;
    --muted: #9da5b4;
    --accent: #7aa2f7;
    --accent-soft: rgba(122, 162, 247, .14);
    --warning: #e0af68;
    --error: #f7768e;
    --line-height: 23px;
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--text); font-family: Inter, ui-sans-serif, system-ui, sans-serif; overflow: hidden; }
  button, input { font: inherit; }
  button { color: inherit; }
  #app { height: 100vh; display: grid; grid-template-rows: 48px minmax(0, 1fr); }
  .topbar { display: flex; align-items: center; gap: 16px; padding: 0 14px; border-bottom: 1px solid var(--border); background: var(--panel); }
  .brand { font-weight: 700; white-space: nowrap; }
  .metrics { display: flex; gap: 8px; flex: 1; min-width: 0; }
  .metric { padding: 3px 8px; border: 1px solid var(--border); border-radius: 6px; color: var(--muted); font-size: 12px; white-space: nowrap; }
  .search-wrap { display: flex; align-items: center; gap: 7px; font-size: 12px; color: var(--muted); }
  input[type="search"] { width: 220px; background: var(--panel-2); color: var(--text); border: 1px solid var(--border); border-radius: 6px; padding: 6px 9px; outline: none; }
  input[type="search"]:focus { border-color: var(--accent); }
  .check { font-size: 12px; color: var(--muted); white-space: nowrap; }
  .workspace { min-height: 0; display: grid; grid-template-columns: 280px minmax(440px, 1fr) 340px; }
  .sidebar, .inspector { min-width: 0; background: var(--panel); overflow: auto; }
  .sidebar { border-right: 1px solid var(--border); }
  .inspector { border-left: 1px solid var(--border); padding-bottom: 24px; }
  .pane-title { position: sticky; top: 0; z-index: 4; background: var(--panel); padding: 10px 12px; color: var(--muted); font-size: 11px; letter-spacing: .08em; border-bottom: 1px solid var(--border); }
  .tree { padding: 6px 0 20px; font-size: 13px; }
  .tree-node { user-select: none; }
  .folder-row, .file-row { min-height: 27px; display: flex; align-items: center; gap: 6px; padding-right: 8px; white-space: nowrap; }
  .folder-row:hover, .file-row:hover { background: rgba(255,255,255,.045); }
  .folder-toggle, .file-button { border: 0; background: transparent; text-align: left; cursor: pointer; padding: 3px 0; min-width: 0; }
  .folder-toggle { flex: 1; }
  .file-button { flex: 1; overflow: hidden; text-overflow: ellipsis; }
  .file-row.active { background: var(--accent-soft); }
  .folder-children.collapsed { display: none; }
  .chevron { width: 14px; color: var(--muted); text-align: center; }
  .file-icon { color: var(--muted); width: 14px; }
  .tree-badge { margin-left: auto; font-size: 10px; color: var(--muted); }
  .tree-badge.warning { color: var(--warning); }
  .tree-badge.error { color: var(--error); }
  .editor-pane { min-width: 0; min-height: 0; display: grid; grid-template-rows: 44px auto minmax(0, 1fr); background: var(--bg); }
  .filebar { display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 0 12px; border-bottom: 1px solid var(--border); background: var(--panel); min-width: 0; }
  .filebar > div:first-child { min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .muted { color: var(--muted); font-size: 12px; }
  .tabs { display: flex; align-self: stretch; }
  .tab { border: 0; border-bottom: 2px solid transparent; background: transparent; padding: 0 13px; cursor: pointer; color: var(--muted); }
  .tab.active { color: var(--text); border-bottom-color: var(--accent); }
  .notice { padding: 8px 12px; background: rgba(224,175,104,.12); color: var(--warning); border-bottom: 1px solid var(--border); font-size: 12px; }
  .hidden { display: none !important; }
  .view { display: none; min-height: 0; }
  .view.active { display: block; }
  .code-viewport { position: relative; width: 100%; height: 100%; overflow: auto; font: 13px/var(--line-height) "Cascadia Code", "SFMono-Regular", Consolas, monospace; outline: none; }
  .code-canvas { position: relative; width: 100%; min-width: max-content; }
  .code-line { position: absolute; left: 0; right: 0; height: var(--line-height); display: grid; grid-template-columns: 66px 86px minmax(600px, 1fr); align-items: stretch; }
  .code-line:hover { background: rgba(255,255,255,.035); }
  .code-line.selected { background: var(--accent-soft); }
  .code-line.unit-start { box-shadow: inset 0 1px 0 var(--accent); }
  .code-line.unit-end { border-bottom: 1px dashed rgba(122,162,247,.45); }
  .line-no { padding: 0 10px 0 4px; color: #6f7785; text-align: right; border-right: 1px solid var(--border); }
  .markers { display: flex; align-items: center; gap: 3px; padding: 0 5px; border-right: 1px solid var(--border); overflow: hidden; }
  .marker { border: 1px solid var(--accent); background: var(--accent-soft); color: var(--text); border-radius: 4px; padding: 0 4px; height: 17px; font: 10px/15px ui-monospace, monospace; cursor: pointer; white-space: nowrap; }
  .marker.warning { border-color: var(--warning); }
  .code-text { white-space: pre; padding: 0 14px 0 10px; color: var(--text); }
  .unit-toolbar { height: 44px; display: flex; align-items: center; gap: 12px; padding: 0 12px; border-bottom: 1px solid var(--border); }
  .unit-toolbar label { font-size: 12px; color: var(--muted); }
  .unit-toolbar input { margin-left: 6px; width: 260px; }
  .unit-list { position: relative; height: calc(100% - 44px); overflow: auto; }
  .unit-list-canvas { position: relative; width: 100%; }
  .unit-row { position: absolute; left: 8px; right: 8px; height: 42px; display: grid; grid-template-columns: 84px 92px 1fr 66px; gap: 8px; align-items: center; padding: 7px 9px; border: 0; border-bottom: 1px solid var(--border); background: transparent; text-align: left; cursor: pointer; font-family: ui-monospace, monospace; font-size: 12px; }
  .unit-row:hover, .unit-row.active { background: var(--accent-soft); }
  .badge { display: inline-flex; align-items: center; border: 1px solid var(--border); border-radius: 999px; padding: 2px 7px; color: var(--muted); font-size: 11px; }
  .warning-dot { color: var(--warning); }
  .empty { padding: 18px 14px; color: var(--muted); font-size: 13px; }
  #unitInspector { padding: 12px; }
  .inspector-head { display: flex; align-items: center; justify-content: space-between; gap: 8px; margin-bottom: 12px; }
  .inspector-head strong { font: 12px ui-monospace, monospace; overflow-wrap: anywhere; }
  .meta-grid { display: grid; grid-template-columns: 54px 1fr; gap: 5px 8px; margin: 0 0 14px; font-size: 12px; }
  .meta-grid dt { color: var(--muted); }
  .meta-grid dd { margin: 0; overflow-wrap: anywhere; }
  .inspector h3 { margin: 16px 0 7px; font-size: 12px; color: var(--muted); font-weight: 600; }
  .inspector pre { margin: 0; padding: 10px; border: 1px solid var(--border); background: var(--panel-2); border-radius: 6px; white-space: pre-wrap; overflow-wrap: anywhere; font: 12px/1.55 "Cascadia Code", Consolas, monospace; }
  .inspector details { margin-top: 12px; }
  .inspector summary { cursor: pointer; color: var(--muted); font-size: 12px; margin-bottom: 7px; }
  .warning-box { padding: 8px 10px; border: 1px solid var(--warning); border-radius: 6px; color: var(--warning); font-size: 12px; }
  .child-list { display: grid; gap: 5px; }
  .child-button { border: 1px solid var(--border); background: var(--panel-2); color: var(--text); border-radius: 5px; padding: 6px 8px; text-align: left; cursor: pointer; font: 11px ui-monospace, monospace; }
  .child-button:hover { border-color: var(--accent); }
  @media (max-width: 1100px) {
    .workspace { grid-template-columns: 240px minmax(420px, 1fr); }
    .inspector { display: none; }
    .metrics, .check { display: none; }
  }
</style>

<script>
(() => {
  const state = {
    meta: null,
    files: [],
    filteredFiles: [],
    activeFile: null,
    fileData: null,
    sourceLines: [],
    markers: [],
    markerById: new Map(),
    starts: new Map(),
    ends: new Map(),
    selectedUnitId: null,
    selectedRange: null,
    lineHeight: 23,
    renderQueued: false,
    filteredMarkers: [],
    unitRowHeight: 42,
    unitRenderQueued: false,
  };

  const $ = (id) => document.getElementById(id);
  const metrics = $('metrics');
  const tree = $('tree');
  const codeViewport = $('codeViewport');
  const codeCanvas = $('codeCanvas');
  const unitList = $('unitList');
  const unitListCanvas = $('unitListCanvas');

  async function api(path) {
    const response = await fetch(path);
    const payload = await response.json();
    if (!response.ok) throw new Error(payload.message || payload.error || response.statusText);
    return payload;
  }

  function esc(value) {
    return String(value ?? '').replace(/[&<>"']/g, (char) => ({
      '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
    })[char]);
  }

  function formatNumber(value) {
    return new Intl.NumberFormat('ko-KR').format(value || 0);
  }

  async function init() {
    try {
      const [meta, filePayload] = await Promise.all([api('/api/meta'), api('/api/files')]);
      state.meta = meta;
      state.files = filePayload.files;
      const summary = meta.summary || {};
      metrics.innerHTML = [
        ['files', summary.file_count ?? meta.indexed_file_count],
        ['units', summary.unit_count ?? meta.indexed_unit_count],
        ['parse errors', summary.parse_error_file_count],
        ['warnings', summary.warning_count],
      ].map(([label, value]) => `<span class="metric">${label}: ${formatNumber(value)}</span>`).join('');
      applyFileFilter();
      const first = state.filteredFiles[0];
      if (first) selectFile(first.file);
    } catch (error) {
      $('notice').textContent = error.message;
      $('notice').classList.remove('hidden');
    }
  }

  function applyFileFilter() {
    const query = $('fileSearch').value.trim().toLowerCase();
    const warningOnly = $('warningOnly').checked;
    const errorOnly = $('errorOnly').checked;
    state.filteredFiles = state.files.filter((file) => {
      if (query && !file.file.toLowerCase().includes(query)) return false;
      if (warningOnly && !file.warning_count) return false;
      if (errorOnly && !file.parse_has_error) return false;
      return true;
    });
    $('visibleFileCount').textContent = `(${formatNumber(state.filteredFiles.length)})`;
    renderTree();
  }

  function buildTree(files) {
    const root = { name: '', folders: new Map(), files: [] };
    for (const file of files) {
      const parts = file.file.split('/');
      let node = root;
      for (const part of parts.slice(0, -1)) {
        if (!node.folders.has(part)) node.folders.set(part, { name: part, folders: new Map(), files: [] });
        node = node.folders.get(part);
      }
      node.files.push({ ...file, name: parts.at(-1) });
    }
    return root;
  }

  function renderTree() {
    const model = buildTree(state.filteredFiles);
    tree.innerHTML = '';
    tree.appendChild(renderTreeNode(model, 0, true));
  }

  function renderTreeNode(node, depth, isRoot = false) {
    const fragment = document.createDocumentFragment();
    for (const folder of [...node.folders.values()].sort((a, b) => a.name.localeCompare(b.name))) {
      const wrap = document.createElement('div');
      wrap.className = 'tree-node';
      const row = document.createElement('div');
      row.className = 'folder-row';
      row.style.paddingLeft = `${8 + depth * 14}px`;
      const chev = document.createElement('span');
      chev.className = 'chevron';
      chev.textContent = '▾';
      const button = document.createElement('button');
      button.type = 'button';
      button.className = 'folder-toggle';
      button.textContent = folder.name;
      const children = document.createElement('div');
      children.className = 'folder-children';
      children.appendChild(renderTreeNode(folder, depth + 1));
      const toggle = () => {
        children.classList.toggle('collapsed');
        chev.textContent = children.classList.contains('collapsed') ? '▸' : '▾';
      };
      row.addEventListener('click', toggle);
      row.append(chev, button);
      wrap.append(row, children);
      fragment.appendChild(wrap);
    }
    for (const file of [...node.files].sort((a, b) => a.name.localeCompare(b.name))) {
      const row = document.createElement('div');
      row.className = 'file-row' + (state.activeFile === file.file ? ' active' : '');
      row.style.paddingLeft = `${8 + depth * 14}px`;
      row.dataset.path = file.file;
      const icon = document.createElement('span');
      icon.className = 'file-icon';
      icon.textContent = file.parse_has_error ? '!' : '·';
      const button = document.createElement('button');
      button.type = 'button';
      button.className = 'file-button';
      button.textContent = file.name;
      button.title = file.file;
      const badges = document.createElement('span');
      badges.className = 'tree-badge' + (file.parse_has_error ? ' error' : file.warning_count ? ' warning' : '');
      badges.textContent = file.parse_has_error ? `E ${file.unit_count}` : file.warning_count ? `W${file.warning_count} ${file.unit_count}` : String(file.unit_count);
      row.addEventListener('click', () => selectFile(file.file));
      row.append(icon, button, badges);
      fragment.appendChild(row);
    }
    return fragment;
  }

  async function selectFile(filePath) {
    state.activeFile = filePath;
    state.selectedUnitId = null;
    state.selectedRange = null;
    renderTree();
    $('activeFile').textContent = filePath;
    $('fileMeta').textContent = ' 불러오는 중...';
    codeCanvas.innerHTML = '';
    unitList.innerHTML = '';
    try {
      const data = await api(`/api/file?path=${encodeURIComponent(filePath)}`);
      state.fileData = data;
      state.sourceLines = data.source_available ? data.source.split(/\r?\n/) : [];
      state.markers = data.markers || [];
      state.markerById = new Map(state.markers.map((marker) => [marker.id, marker]));
      state.starts = groupMarkers(
        state.markers,
        'display_start_line',
      );
      state.ends = groupMarkers(
        state.markers,
        'display_end_line',
      );
      $('fileMeta').textContent = ` · ${data.language} · ${formatNumber(data.unit_count)} units${data.warning_count ? ` · ${data.warning_count} warnings` : ''}${data.parse_has_error ? ' · parse error' : ''}`;
      showNotice(data);
      renderUnitList();
      if (data.source_available) {
        codeCanvas.style.height = `${Math.max(1, state.sourceLines.length) * state.lineHeight}px`;
        codeViewport.scrollTop = 0;
        renderVisibleLines();
      } else {
        codeCanvas.style.height = '100%';
        codeCanvas.innerHTML = `<div class="empty">${esc(data.source_error || '원본 소스를 읽을 수 없습니다.')}</div>`;
        switchTab('units');
      }
    } catch (error) {
      $('notice').textContent = error.message;
      $('notice').classList.remove('hidden');
    }
  }

  function groupMarkers(markers, field) {
    const map = new Map();
    for (const marker of markers) {
      const line = marker[field];
      if (!map.has(line)) map.set(line, []);
      map.get(line).push(marker);
    }
    return map;
  }

  function showNotice(data) {
    const notice = $('notice');
    const messages = [];
    if (data.parse_has_error) messages.push(`파싱 오류가 있습니다: ${data.diagnostics.length}개 진단`);
    if (!data.source_available) messages.push(data.source_error || '원본 파일을 찾지 못했습니다.');
    if (messages.length) {
      notice.textContent = messages.join(' · ');
      notice.classList.remove('hidden');
    } else {
      notice.classList.add('hidden');
    }
  }

  function renderVisibleLines() {
    if (!state.fileData?.source_available) return;
    const total = state.sourceLines.length;
    const viewportHeight = codeViewport.clientHeight || 600;
    const overscan = 40;
    const start = Math.max(0, Math.floor(codeViewport.scrollTop / state.lineHeight) - overscan);
    const end = Math.min(total, Math.ceil((codeViewport.scrollTop + viewportHeight) / state.lineHeight) + overscan);
    const fragment = document.createDocumentFragment();

    for (let index = start; index < end; index++) {
      const lineNumber = index + 1;
      const starts = state.starts.get(lineNumber) || [];
      const ends = state.ends.get(lineNumber) || [];
      const row = document.createElement('div');
      row.className = 'code-line';
      if (starts.length) row.classList.add('unit-start');
      if (ends.length) row.classList.add('unit-end');
      if (state.selectedRange && lineNumber >= state.selectedRange[0] && lineNumber <= state.selectedRange[1]) row.classList.add('selected');
      row.style.top = `${index * state.lineHeight}px`;
      row.dataset.line = String(lineNumber);

      const lineNo = document.createElement('div');
      lineNo.className = 'line-no';
      lineNo.textContent = String(lineNumber);
      const markerBox = document.createElement('div');
      markerBox.className = 'markers';
      for (const marker of starts.slice(0, 2)) {
        const button = document.createElement('button');
        button.type = 'button';
        button.className = 'marker' + (marker.warning_count ? ' warning' : '');
        button.textContent = marker.kind.slice(0, 3);
        button.title = `${marker.id}
${marker.kind} · display ${marker.display_start_line}-${marker.display_end_line}
source ${marker.start_line}-${marker.end_line}`;
        button.addEventListener('click', (event) => {
          event.stopPropagation();
          selectUnit(marker.id, true);
        });
        markerBox.appendChild(button);
      }
      if (starts.length > 2) {
        const more = document.createElement('button');
        more.type = 'button';
        more.className = 'marker';
        more.textContent = `+${starts.length - 2}`;
        more.title = starts.slice(2).map((m) => m.id).join('\n');
        more.addEventListener('click', (event) => {
          event.stopPropagation();
          selectUnit(starts[2].id, true);
        });
        markerBox.appendChild(more);
      }
      const code = document.createElement('div');
      code.className = 'code-text';
      code.textContent = state.sourceLines[index] || '';
      row.addEventListener('click', () => {
        const candidates = starts.length
          ? starts
          : state.markers.filter(
              (marker) =>
                marker.display_start_line <= lineNumber
                && marker.display_end_line >= lineNumber,
            );
        if (candidates.length) {
          const best = [...candidates].sort(
            (a, b) =>
              b.depth - a.depth
              || (
                a.display_end_line - a.display_start_line
              ) - (
                b.display_end_line - b.display_start_line
              ),
          )[0];
          selectUnit(best.id, false);
        }
      });
      row.append(lineNo, markerBox, code);
      fragment.appendChild(row);
    }
    codeCanvas.replaceChildren(fragment);
  }

  function queueLineRender() {
    if (state.renderQueued) return;
    state.renderQueued = true;
    requestAnimationFrame(() => {
      state.renderQueued = false;
      renderVisibleLines();
    });
  }

  function renderUnitList() {
    const query = $('unitSearch').value.trim().toLowerCase();
    state.filteredMarkers = state.markers.filter((marker) => {
      if (!query) return true;
      return marker.id.toLowerCase().includes(query)
        || marker.kind.toLowerCase().includes(query)
        || marker.node_type.toLowerCase().includes(query)
        || String(marker.start_line).includes(query)
        || String(marker.end_line).includes(query);
    });
    $('unitCountLabel').textContent = `${formatNumber(state.filteredMarkers.length)} / ${formatNumber(state.markers.length)}`;
    unitListCanvas.style.height = `${state.filteredMarkers.length * state.unitRowHeight}px`;
    unitList.scrollTop = 0;
    renderVisibleUnits();
  }

  function renderVisibleUnits() {
    const total = state.filteredMarkers.length;
    const viewportHeight = unitList.clientHeight || 500;
    const overscan = 20;
    const start = Math.max(0, Math.floor(unitList.scrollTop / state.unitRowHeight) - overscan);
    const end = Math.min(total, Math.ceil((unitList.scrollTop + viewportHeight) / state.unitRowHeight) + overscan);
    const fragment = document.createDocumentFragment();
    for (let index = start; index < end; index++) {
      const marker = state.filteredMarkers[index];
      const button = document.createElement('button');
      button.type = 'button';
      button.className = 'unit-row' + (state.selectedUnitId === marker.id ? ' active' : '');
      button.dataset.id = marker.id;
      button.style.top = `${index * state.unitRowHeight}px`;
      button.innerHTML = `
        <span>${marker.display_start_line}-${marker.display_end_line}</span>
        <span class="badge">${esc(marker.kind)}</span>
        <span style="padding-left:${Math.min(marker.depth, 8) * 10}px">${esc(marker.node_type)}</span>
        <span>${marker.warning_count ? '<span class="warning-dot">warning</span>' : `d${marker.depth}`}</span>
      `;
      button.addEventListener('click', () => selectUnit(marker.id, true));
      fragment.appendChild(button);
    }
    unitListCanvas.replaceChildren(fragment);
  }

  function queueUnitRender() {
    if (state.unitRenderQueued) return;
    state.unitRenderQueued = true;
    requestAnimationFrame(() => {
      state.unitRenderQueued = false;
      renderVisibleUnits();
    });
  }

  async function selectUnit(unitId, scrollToLine) {
    const marker = state.markerById.get(unitId);
    if (!marker) return;
    state.selectedUnitId = unitId;
    state.selectedRange = [
      marker.display_start_line,
      marker.display_end_line,
    ];
    if (scrollToLine && state.fileData?.source_available) {
      codeViewport.scrollTop = Math.max(
        0,
        (marker.display_start_line - 2) * state.lineHeight,
      );
    }
    renderVisibleLines();
    renderVisibleUnits();
    try {
      const unit = await api(`/api/unit?id=${encodeURIComponent(unitId)}`);
      renderInspector(unit);
    } catch (error) {
      $('notice').textContent = error.message;
      $('notice').classList.remove('hidden');
    }
  }

  function renderInspector(unit) {
    $('emptyInspector').classList.add('hidden');
    $('unitInspector').classList.remove('hidden');
    $('unitId').textContent = unit.id;
    $('unitKind').textContent = unit.kind;
    const sourceRange = `${unit.start_line}:${unit.start_column} → ${unit.end_line}:${unit.end_column}`;
    const displayRange = `${unit.display_start_line} → ${unit.display_end_line}`;

    $('unitLines').textContent =
      unit.start_line === unit.display_start_line
      && unit.end_line === unit.display_end_line
        ? sourceRange
        : `${displayRange} · source ${sourceRange}`;
    $('unitNode').textContent = unit.node_type;
    $('unitDepth').textContent = String(unit.depth);
    $('unitParent').textContent = unit.parent_id || '-';
    $('unitRole').textContent = unit.scope_role || '-';
    $('unitCode').textContent = unit.code;
    $('unitRaw').textContent = unit.raw_code;
    const warningBox = $('unitWarnings');
    if (unit.warnings?.length) {
      warningBox.textContent = unit.warnings.join('\n');
      warningBox.classList.remove('hidden');
    } else {
      warningBox.classList.add('hidden');
    }
    const wrap = $('unitChildrenWrap');
    const childrenEl = $('unitChildren');
    if (unit.children?.length) {
      childrenEl.innerHTML = '';
      for (const child of unit.children) {
        const button = document.createElement('button');
        button.type = 'button';
        button.className = 'child-button';
        button.textContent =
          `${child.display_start_line}-${child.display_end_line}`
          + ` · ${child.kind} · ${child.id}`;
        button.addEventListener('click', () => selectUnit(child.id, true));
        childrenEl.appendChild(button);
      }
      wrap.classList.remove('hidden');
    } else {
      wrap.classList.add('hidden');
    }
  }

  function switchTab(name) {
    const source = name === 'source';
    $('sourceTab').classList.toggle('active', source);
    $('unitsTab').classList.toggle('active', !source);
    $('sourceView').classList.toggle('active', source);
    $('unitsView').classList.toggle('active', !source);
    if (source) queueLineRender();
    else queueUnitRender();
  }

  $('fileSearch').addEventListener('input', applyFileFilter);
  $('warningOnly').addEventListener('change', applyFileFilter);
  $('errorOnly').addEventListener('change', applyFileFilter);
  $('unitSearch').addEventListener('input', renderUnitList);
  $('sourceTab').addEventListener('click', () => switchTab('source'));
  $('unitsTab').addEventListener('click', () => switchTab('units'));
  codeViewport.addEventListener('scroll', queueLineRender);
  unitList.addEventListener('scroll', queueUnitRender);
  window.addEventListener('resize', queueLineRender);

  init();
})();
</script>'''


if __name__ == "__main__":
    raise SystemExit(main())
